on:
  - workflow_dispatch
  - create
permissions:
  id-token: write
  actions: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
jobs:
  build_linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.15.0"
      - run: |
          sudo apt update
          sudo apt install fuse libopengl0 libegl1 libxcb1 libxkbcommon-x11-0 libxcb-glx0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-render0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-util1 libxcb-xfixes0 libxcb-xkb1 libxdmcp6
      - name: npm install, build and test
        run: |
          npm install
          npm run build
      - name: deploy
        run: |
          npx nodegui-packer -p dist
      - name: hash
        run: |
          echo SHA1
          sha1sum deploy/linux/build/DMCLQT/*.AppImage
          echo SHA256
          sha256sum deploy/linux/build/DMCLQT/*.AppImage
      - uses: actions/upload-artifact@v3
        with:
          name: Linux
          path: deploy/linux/build/DMCLQT/*.AppImage
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.15.0"
      - name: npm install, build and test
        run: |
          npm install
          npm run build
      - name: deploy
        run: |
          npx nodegui-packer -p dist
      - name: hash
        run: |
          echo SHA1
          bash -c "find deploy/win32/build/DMCLQT -type f | xargs sha1sum"
          echo SHA256
          bash -c "find deploy/win32/build/DMCLQT -type f | xargs sha256sum"
      - uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: deploy/win32/build/DMCLQT
  build_darwin:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.15.0"
      - name: npm install, build and test
        run: |
          npm install
          npm run build
      - name: deploy
        run: |
          npx nodegui-packer -p dist
      - name: hash
        run: |
          echo SHA1
          shasum deploy/darwin/build/DMCLQT.dmg
          echo SHA256
          shasum -a 256 deploy/darwin/build/DMCLQT.dmg
      - uses: actions/upload-artifact@v3
        with:
          name: MacOS
          path: deploy/darwin/build/DMCLQT.dmg
  create_release:
    needs:
      - build_windows
      - build_linux
      - build_darwin
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' && !contains(github.ref_name, '-') }}
    steps:
    - uses: actions/download-artifact@v3
    - name: tar
      run: |
        tar cvfJ windows.tar.xz Windows
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          windows.tar.xz
          Linux/*.AppImage
          MacOS/DMCLQT.dmg
