on: [create, workflow_dispatch]
permissions:
  id-token: write
  actions: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
jobs:
  build_linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.15.0"
      - run: |
          sudo apt update
          sudo apt install fuse libopengl0 libegl1 xbc libicu66 libgcrypt20 libbsd0 libdbus-1-3 libglib2.0-0 liblz4-1 liblzma5 libpcre3 libpng16-16 libsystemd0
      - name: npm install, build and test
        run: |
          npm install
          npm run build
      - name: deploy
        run: |
          npx nodegui-packer -i DMCLQT
          npx nodegui-packer -p dist
      - uses: actions/upload-artifact@v3
        with:
          name: Linux
          path: deploy/linux/build/DMCLQT/Application-x86_64.AppImage
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.15.0"
      - name: npm install, build and test
        run: |
          npm install
          npm run build
      - name: deploy
        run: |
          npx nodegui-packer -i DMCLQT
          npx nodegui-packer -p dist
      - uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: deploy/win32/build/DMCLQT
  build_darwin:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.15.0"
      - name: npm install, build and test
        run: |
          npm install
          npm run build
      - name: deploy
        run: |
          npx nodegui-packer -i DMCLQT
          npx nodegui-packer -p dist
      - uses: actions/upload-artifact@v3
        with:
          name: MacOS
          path: deploy/darwin/build
