on: [create, workflow_dispatch]
permissions:
  id-token: write
  actions: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
jobs:
  build_linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.15.0"
      - run: |
          sudo apt update
          sudo apt install fuse libopengl0 libegl1 libxcb1 libxkbcommon-x11-0 libxcb-glx0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-render0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-util1 libxcb-xfixes0 libxcb-xkb1 libxdmcp6
      - name: npm install, build and test
        run: |
          npm install
          npm run build
      - name: deploy
        run: |
          npx nodegui-packer -i DMCLQT
          sed -i 's/\r//' deploy/linux/DMCLQT/default.desktop
          npx nodegui-packer -p dist
          sha1sum deploy/linux/build/DMCLQT/*.AppImage
          sha256sum deploy/linux/build/DMCLQT/*.AppImage
      - uses: actions/upload-artifact@v3
        with:
          name: Linux
          path: deploy/linux/build/DMCLQT/*.AppImage
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.15.0"
      - name: npm install, build and test
        run: |
          npm install
          npm run build
      - name: deploy
        run: |
          npx nodegui-packer -i DMCLQT
          npx nodegui-packer -p dist
          find deploy/win32/build/DMCLQT | xargs sha1sum
      - uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: deploy/win32/build/DMCLQT
  build_darwin:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.15.0"
      - name: npm install, build and test
        run: |
          npm install
          npm run build
      - name: deploy
        run: |
          npx nodegui-packer -i DMCLQT
          npx nodegui-packer -p dist
          find deploy/darwin/build | xargs shasum
      - uses: actions/upload-artifact@v3
        with:
          name: MacOS
          path: deploy/darwin/build
